const express = require("express")
const mongoose = require("mongoose")
const jwt = require("jsonwebtoken")
mongoose.connect("mongodb://localhost/assignment")
const app = express()
const postsRoutes = require("./routes/posts")
const loginRoutes = require("./routes/login")
app.use("/posts", postsRoutes)
app.use("/", loginRoutes)
app.listen(3000, () => console.log("The server is up at 3000"))